os: osx
osx_image: xcode11.3
language: node_js
node_js: '10'
jobs:
  include:
    - stage: release
      if: tag IS present
      before_deploy:
      - HOMEBREW_NO_AUTO_UPDATE=1 brew install rpm
      - yarn dist
      deploy:
        provider: releases
        skip_cleanup: true
        api_key:
          secure: taeE9KccF5UVwjE81w1ltTaiR04DsJjalwqfiU3ekoeuO3PaxpuPpJXCGynOSmGXuKEFRxdmrqEmCBanfGp0r4gpjhvtr6YQZK7GCff9kJ2/xSOgHqsAzAa7OoCMWIFXmSVHbEBo2awpI3003w3jW9yjjOtHN6lVEVa1X6GMm6Y2PL1rDsPbeyb9Mocr42ryQ8UOT0qMgJjk+FbOh/JypRMhqj7p7xB7PihQLbVhBmUmcC8ebd3Q7x2IZ11Ka4hCY/aWylf9ufyeI4ORzzCtIDB1uFjG8NeqBZ5ad9tnpShbnvIjapVfj00wSVUtinFOI524u6fBAapUs/B87eO3vXOTWL+BrEZDClXqe2fTVK1T8zlO+rmq8o9IrWCsiwwa1vChEO+tYVo3r2PTPA4d7CScMHwC0R5Xw1CbSzGteZr4OAbdLCDtaJPC9w+tJZQaXFE3wwIGU+r/LR6Lvog7lrdXLzga9bnpZUSZKJ2IbweiUazKewYLBXxukk+m6NMIW2FEbyoaHslGVsBSIllW2WzZXQAdzeQhXqJcA4Dv64qjewtjLyeG+Q5CrwM2HSN4vPdj6hhjHYVjrGBsfUcr8iq8TLIbtxdbr89eAWpeEHh+ZeAOxl3yMjtuZkOF64Ih9HcqZtL4cq2rUY5YGL6mQCKxbtrOc7JMRCyAAfD/hR8=
        keep_history: true
        file_glob: true
        file: dist/*
        on:
          tags: true
